# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: 'main'
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: cd laradump-ui && rm package-lock.json
      - run: cd laradump-ui && npm install
      - run: npm install -g sass
      - run: rm package-lock.json
      - run: npm install
      - run: npm run ui-build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
